### ISSUE TITLE
Create copyable, non editable inputfield with decrypt url

### ISSUE THREAD

**Issue by Julius-Bendt** [Neophear/cryptique-web#1]
Something like `https://cryptique.dev/decrypt?id=xxxx&key=xxxx` maybe key or id could be dismissed for security

That way, I only have to write copy paste a one or two string in order to decrypt

**Comment by Neophear** [comment]
Already working (although fixed issue with SPA routing)
![image](https://github.com/Neophear/cryptique-web/assets/26252347/044cd4cd-d30f-4256-9e73-733acea91abb)

Its not readonly though, but that is just UX friendlyness, as the functionality is there.

**Comment by Julius-Bendt** [comment]
What I was thinking, was that this input field would also create the url:
![image](https://github.com/Neophear/cryptique-web/assets/22844949/e3dcad73-d50c-4db9-ada1-02eadf37deeb)

**Comment by Neophear** [comment]
Ah of course! That is also planned to be implemented. Havent come to it yet, but good with and issue, so I remember
